config/routes.rb
Rails.application.routes.draw do
  resources :characters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "characters#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
  has_one_attached :image
  validates :name, presence: true
  validates :year, presence: true, numericality: { minimum: 1699, maximum: 2199 }
  validates :film, presence: true
  validates :quote, presence: true
  validates :rating, presence: true, numericality: { minimum: 1.0, maximum: 10.0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[ show edit update destroy ]

  # GET /characters or /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1 or /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters or /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: "Character was successfully created." }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1 or /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: "Character was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1 or /characters/1.json
  def destroy
    @character.destroy!

    respond_to do |format|
      format.html { redirect_to characters_path, notice: "Character was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def character_params
      params.expect(character: [ :name, :year, :film, :description, :quote, :rating, :image ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_character.html.erb
<div id="<%= dom_id character %>" class="w-full sm:w-auto my-5 space-y-5">
  <% if character.image.attached? %>
    <%= image_tag character.image.variant(:thumb),
    class: "w-32 h-32 object-cover rounded-lg" %>
  <% else %>
    <p>Ain't narry notter no pickshure</p>
  <% end %>
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= character.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Year:</strong>
    <%= character.year %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Film:</strong>
    <%= character.film %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Description:</strong>
    <%= character.description %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Quote:</strong>
    <%= character.quote %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Rating:</strong>
    <%= character.rating %>
  </div>
</div>

app/views/characters/_form.html.erb
<%= form_with(model: character, class: "contents") do |form| %>
  <% if character.errors.any? %>
    <div
      id="error_explanation"
      class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3"
    >
      <h2><%= pluralize(character.errors.count, "error") %>
        prohibited this character from being saved:</h2>

      <ul class="list-disc ml-6">
        <% character.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name,
                    class: [
                      "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full",
                      {
                        "border-gray-400 focus:outline-blue-600":
                          character.errors[:name].none?,
                        "border-red-400 focus:outline-red-600":
                          character.errors[:name].any?,
                      },
                    ] %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image,
                    class: [
                      "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full",
                      {
                        "border-gray-400 focus:outline-blue-600":
                          character.errors[:name].none?,
                        "border-red-400 focus:outline-red-600":
                          character.errors[:name].any?,
                      },
                    ] %>
  </div>

  <div class="my-5">
    <%= form.label :year %>
    <%= form.number_field :year,
                      class: [
                        "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full",
                        {
                          "border-gray-400 focus:outline-blue-600":
                            character.errors[:year].none?,
                          "border-red-400 focus:outline-red-600":
                            character.errors[:year].any?,
                        },
                      ] %>
  </div>

  <div class="my-5">
    <%= form.label :film %>
    <%= form.text_field :film,
                    class: [
                      "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full",
                      {
                        "border-gray-400 focus:outline-blue-600":
                          character.errors[:film].none?,
                        "border-red-400 focus:outline-red-600":
                          character.errors[:film].any?,
                      },
                    ] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description,
                    class: [
                      "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full",
                      {
                        "border-gray-400 focus:outline-blue-600":
                          character.errors[:description].none?,
                        "border-red-400 focus:outline-red-600":
                          character.errors[:description].any?,
                      },
                    ] %>
  </div>

  <div class="my-5">
    <%= form.label :quote %>
    <%= form.text_field :quote,
                    class: [
                      "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full",
                      {
                        "border-gray-400 focus:outline-blue-600":
                          character.errors[:quote].none?,
                        "border-red-400 focus:outline-red-600":
                          character.errors[:quote].any?,
                      },
                    ] %>
  </div>

  <div class="my-5">
    <%= form.label :rating %>
    <%= form.text_field :rating,
                    class: [
                      "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full",
                      {
                        "border-gray-400 focus:outline-blue-600":
                          character.errors[:rating].none?,
                        "border-red-400 focus:outline-red-600":
                          character.errors[:rating].any?,
                      },
                    ] %>
  </div>

  <div class="inline">
    <%= form.submit class:
                  "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<% content_for :title, "Editing character" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing character</h1>

  <%= render "form", character: @character %>

  <%= link_to "Show this character", @character, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to characters", characters_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/characters/index.html.erb
<% content_for :title, "Characters" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Characters</h1>
    <%= link_to "New character", new_character_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="characters" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @characters.any? %>
      <% @characters.each do |character| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render character %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", character, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_character_path(character), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", character, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No characters found.</p>
    <% end %>
  </div>
</div>

app/views/characters/new.html.erb
<% content_for :title, "New character" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New character</h1>

  <%= render "form", character: @character %>

  <%= link_to "Back to characters", characters_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/characters/show.html.erb
<% content_for :title, "Showing character" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing character</h1>

  <%= render @character %>

  <%= link_to "Edit this character", edit_character_path(@character), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to characters", characters_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this character", @character, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cage" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>